from enum import Enum


class ServerReplyCodes(Enum):
    REGISTERED_SUCCESSFULLY = 1600
    REGISTRATION_FAILED = 1601
    PUBLIC_KEY_RECEIVED_SENDING_ENCRYPTED_AES_KEY = 1602
    FILE_RECEIVED_SUCCESSFULLY_WITH_CRC = 1603
    RECEIVE_MESSAGE_THANKS = 1604
    APPROVED_RECONNECT_REQUEST_SENDING_ENCRYPTED_AES_KEY = 1605
    DISAPPROVED_RECONNECT_REQUEST = 1606
    GENERAL_SERVER_ERROR = 1607
