from enum import Enum


class ClientRequestCodes(Enum):
    REGISTER_REQUEST = 825
    SEND_PUBLIC_KEY = 826
    RECONNECT_TO_SERVER = 827
    SEND_FILE = 828
    ADEQUATE_CRC_VALUE = 900
    INADEQUATE_CRC_VALUE = 901
    INADEQUATE_CRC_VALUE_FOR_THE_FORTH_TIME = 902
